server:
  port: 8085
hm:
  swagger:
    title: 黑马商城交易服务接口文档
    description: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller
  db:
    database: hm-trade
spring:
  rabbitmq:
    host: 192.168.74.121
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123

