server:
  port:8080
spring:
  application:
    name:gateway
cloud:
  nacos:
    server-addr: 192.168.159.121:8848
  gateway:
    routes:
      - id: cart-service
        uri: lb://item-service
        predicates:
          - Path=/carts/**

      - id: item-service
        uri: lb://item-service
        predicates:
        - Path=/items/**,/search/**

      - id: pay-service
        uri: lb://user-service
        predicates:
          - Path=/pay-orders/**

      - id: trade-service
        uri: lb://user-service
        predicates:
          - Path=/orders/**

      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/address/**,/users/**
